language: java

sudo: false

jdk:
- openjdk8

before_install:
- chmod +x gradlew

script:
  - ./gradlew clean test -Pci.tags.exclude=!api --debug

notifications:
  email:
    recipients:
      - rogzy1606@gmail.com
    on_success: never
    on_failure: always