language: java

sudo: false

jdk:
- openjdk8

env:
  - debug.mode=true

before_install:
- chmod +x gradlew

script:
  - ./gradlew clean test -Pci.tags.exclude=!api
  - ./gradlew clean test -Pci.tags.exclude=!web

notifications:
  email:
    recipients:
      - rogzy1606@gmail.com
    on_success: never
    on_failure: always